### ISSUE TITLE
考虑共建 JanusGraph 的可视化工具吗

### ISSUE THREAD

**Issue by pomelo-nwu** [fenglex/janusgraph-visualization#34]
嗨，我注意到你的项目 readme 中有
![image](https://user-images.githubusercontent.com/10703060/215403377-50757ac9-42d6-4943-91f8-e76fb157f16c.png)

我是 G6 团队的同学，负责基于 G6 的可视化平台 [G6VP](https://github.com/antvis/G6VP) 的产品建设，目前已经对接了[ TuGraph](https://github.com/TuGraph-db/tugraph-db)，[GraphScope](https://github.com/alibaba/GraphScope)，neo4J 等图数据源。今年也将计划对接JanusGraph，不知道你是否感兴趣参与共建～

**Comment by fenglex** [comment]
可以的啊，不过前端这块并不是我擅长的，这个项目也是当时临时学习的vue写的

**Comment by fenglex** [comment]
> 嗨，我注意到你的项目 readme 中有 ![image](https://user-images.githubusercontent.com/10703060/215403377-50757ac9-42d6-4943-91f8-e76fb157f16c.png)
> 
> 我是 G6 团队的同学，负责基于 G6 的可视化平台 [G6VP](https://github.com/antvis/G6VP) 的产品建设，目前已经对接了[ TuGraph](https://github.com/TuGraph-db/tugraph-db)，[GraphScope](https://github.com/alibaba/GraphScope)，neo4J 等图数据源。今年也将计划对接JanusGraph，不知道你是否感兴趣参与共建～

可以的啊，不过前端这块并不是我擅长的，这个项目也是当时临时学习的vue写的

**Comment by pomelo-nwu** [comment]
@fenglex 我们已经在对接了，预计下个月将上线：https://github.com/antvis/G6VP/pull/310
邀请你测试下全流程，目前还差查询schema和subgraph功能
